### ISSUE TITLE
cannot retrieve sflash0 or any of the devices in /dev

### ISSUE THREAD

**Issue by zecoxao** [ps5-payload-dev/ftpsrv#1]
self explanatory, Sistro's ftp can do this, john's can't

**Comment by john-tornblom** [comment]
The ftp protocol is only intended for regular files, which have a well defined beginning and end, unlike, e.g., /dev/zero. Furthermore, /dev/sflash0 seems to require additional permissions (unlike /dev/zero), any idea what they might be? I would write a simple payload that specifically dumps /dev/sflash0

**Comment by zecoxao** [comment]
i am guessing it requires the regular jailbreak with a specific auth id, but flatz or specter or chendo should know more about this specific auth id
